version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/appuser/app
    ports:
      - 5005:8501
    environment:
      - ENV=development
      - PROJECT_KEY=${PROJECT_KEY}
      - DETA_KEY=${DETA_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_URL=${AWS_URL}
      - AWS_PATH=${AWS_PATH}
      - APP_KEY=${APP_KEY}
      - PRIVATE_KEY_ID=${PRIVATE_KEY_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CLIENT_EMAIL=${CLIENT_EMAIL}
      - CLIENT_ID=${CLIENT_ID}
      - AUTH_PROVIDER_X509_CERT_URL=${AUTH_PROVIDER_X509_CERT_URL}
      - CLIENT_X509_CERT_URL=${CLIENT_X509_CERT_URL}
